sudo: false

language: node_js

node_js:
  - "4.0"

cache:
  directories:
    - elm-stuff/packages
    - libsysconfcpus

install:
  - npm install -g elm@0.18.0
  - npm install -g ahultgren/swagger-elm#v0.3.0
  - npm install -g elm-format@0.5.2
  - |
    if [ ! -d libsysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/libsysconfcpus;
      make && make install;
      cd ..;
    fi
  - elm package install --yes

script:
  - libsysconfcpus/bin/sysconfcpus -n 2 make
